# Generated by Django 4.1.3 on 2023-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
