# Generated by Django 4.1.3 on 2023-02-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='article_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.articlesource'),
        ),
    ]
