# Generated by Django 4.1.3 on 2023-02-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articlesource_remove_article_text_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_source',
        ),
        migrations.DeleteModel(
            name='ArticleSource',
        ),
    ]
