# Generated by Django 4.1.3 on 2023-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_article_source_delete_articlesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(null=True, upload_to='images/news/'),
        ),
    ]
