# Generated by Django 4.1.3 on 2023-02-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_article_slug_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='title',
        ),
    ]
