# Generated by Django 4.1.5 on 2023-01-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_payment_method_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_standart', models.CharField(max_length=10)),
                ('commission', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=150)),
                ('currency_name_short', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='images/coins/')),
                ('category_payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categorypaymentmethod')),
                ('token_standart', models.ManyToManyField(to='main.tokenstandart')),
            ],
        ),
        migrations.CreateModel(
            name='GiveCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=150)),
                ('currency_name_short', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='images/coins/')),
                ('category_payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categorypaymentmethod')),
                ('token_standart', models.ManyToManyField(to='main.tokenstandart')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveGiveCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('give', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.givecurrency')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.receivecurrency')),
            ],
            options={
                'unique_together': {('receive', 'give')},
            },
        ),
    ]
