# Generated by Django 4.1.3 on 2023-02-25 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('give_sum', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('receive_sum', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('give', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.givecurrency')),
                ('give_token_standart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='give_token_standart', to='main.tokenstandart')),
                ('receive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.receivecurrency')),
                ('receive_token_standart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_token_standart', to='main.tokenstandart')),
            ],
        ),
    ]
