# Generated by Django 4.1.3 on 2023-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_give_sum_alter_order_receive_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='give_name',
            field=models.CharField(default='Без имени', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_address',
            field=models.CharField(default='Без имени', max_length=255),
        ),
    ]
