# Generated by Django 4.1.3 on 2023-02-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_give_name_order_receive_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='give_address',
            field=models.CharField(default='Без адреса', max_length=255),
        ),
        migrations.CreateModel(
            name='ReceiveAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Без адреса', max_length=255)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.receivecurrency')),
                ('token_standart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tokenstandart')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.receiveaddress'),
        ),
    ]
