# Generated by Django 4.1.3 on 2023-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_give_address_receiveaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='random_string',
            field=models.CharField(default='Нет строки', max_length=200),
        ),
    ]
