# Generated by Django 4.1.6 on 2023-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_receiveaddress_addressto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressto',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='addressto',
            name='token_standart',
        ),
        migrations.AddField(
            model_name='receivecurrency',
            name='address',
            field=models.ManyToManyField(to='main.addressto'),
        ),
    ]
