# Generated by Django 4.1.6 on 2023-03-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_addressto_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivecurrency',
            name='address',
        ),
        migrations.AddField(
            model_name='receivecurrency',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.addressto'),
        ),
    ]
