# Generated by Django 4.1.6 on 2023-03-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_receivecurrency_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivecurrency',
            name='address',
        ),
        migrations.CreateModel(
            name='AddressToReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.addressto')),
                ('receive_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.receivecurrency')),
            ],
            options={
                'unique_together': {('address', 'receive_currency')},
            },
        ),
    ]
