# Generated by Django 4.1.6 on 2023-03-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_addressto_currency_addressto_token_standart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressto',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.givecurrency'),
        ),
    ]
