# Generated by Django 4.1.6 on 2023-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_orderstatus_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='status', max_length=255),
        ),
    ]
