# Generated by Django 4.1.6 on 2023-04-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='NyTable',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.order')),
            ],
            bases=('main.order',),
        ),
    ]
