# Generated by Django 4.1.6 on 2023-04-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_nytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NyTable',
        ),
    ]
