# Generated by Django 4.1.6 on 2023-04-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_nytable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressto',
            options={'verbose_name': 'Адрес для перевода', 'verbose_name_plural': 'Адреса для перевода'},
        ),
        migrations.AlterModelOptions(
            name='categorypaymentmethod',
            options={'verbose_name': 'Вид платёжной системы', 'verbose_name_plural': 'Виды платёжных систем'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='givecurrency',
            options={'verbose_name': 'Валюта, которую отдаёт клиент', 'verbose_name_plural': 'Валюты, которые отдаёт клиент'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказы', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='receivecurrency',
            options={'verbose_name': 'Валюта, которую получает клиент', 'verbose_name_plural': 'Валюты, которые получает клиент'},
        ),
        migrations.AlterModelOptions(
            name='receivegivecurrencies',
            options={'verbose_name': 'Путь обмена', 'verbose_name_plural': 'Пути обмена'},
        ),
        migrations.AlterModelOptions(
            name='tokenstandart',
            options={'verbose_name': 'Сеть криптовалюты', 'verbose_name_plural': 'Сети криптовалют'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='order',
            order_with_respect_to='give',
        ),
    ]
