# Generated by Django 4.1.6 on 2023-04-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_addressto_options_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='order',
            order_with_respect_to=None,
        ),
    ]
