# Generated by Django 4.1.6 on 2023-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order_main_order_random__bf3f4b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivecurrency',
            name='fund',
            field=models.FloatField(default=0),
        ),
    ]
