# Generated by Django 4.1.6 on 2023-06-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_receivecurrency_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.addressto', verbose_name='Адрес, на который клиент переводит свои деньги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='give',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.givecurrency', verbose_name='Валюта, которую отдаёт клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='give_sum',
            field=models.FloatField(default=0, verbose_name='Cумма, которую отдаёт клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='give_token_standart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='give_token_standart', to='main.tokenstandart', verbose_name='Сеть криптовалюты, которую отдаёт клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Заказ исполнен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='random_string',
            field=models.CharField(default='Нет строки', max_length=200, verbose_name='Ссылка на заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.receivecurrency', verbose_name='Валюта, которую получает клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_address',
            field=models.CharField(default='Без адреса', max_length=255, verbose_name='Адрес кошелька получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_name',
            field=models.CharField(default='Без имени', max_length=255, verbose_name='Имя владельца карты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_sum',
            field=models.FloatField(default=0, verbose_name='Сумма, которую получает клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_token_standart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_token_standart', to='main.tokenstandart', verbose_name='Сеть криптовалюты, которую получает клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
